[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
evohomeclient = "0.3.9"
requests = "2.32.5"

[tool.poetry.group.dev.dependencies]
pytest = "9.0.2"
freezegun = "1.5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["src"]
