EVOHOME_LOCATION_NAME = ""
EVOHOME_USERNAME = ""
EVOHOME_PASSWORD = ""

HOMEASSISTANT_URL = "https://xxx.xxx"
HOMEASSISTANT_TOKEN = ""
HOMEASSISTANT_PRESENCE_ENTITY = "device_tracker.xxx"
HOMEASSISTANT_WEATHER_ENTITY = "weather.xxx"

LAST_HOME_GRACE_TIME = 86400
HEATING_SCHEDULE_GRACE_TIME = 1800
HEATING_SCHEDULE_OFF_TEMP = 15.0
HEATING_ECO_TEMPERATURE = 18.0
HEATING_ECO_TEMPERATURE_OFFSET = 1.0
