EVOHOME_LOCATION_NAME = ""
EVOHOME_SCHEDULE_GRACE_TIME = 1800
EVOHOME_SCHEDULE_OFF_TEMP = 15
EVOHOME_HEATING_ECO_TEMPERATURE = 18
EVOHOME_USERNAME = ""
EVOHOME_PASSWORD = ""

UNIFI_SITE_NAME = "default"
UNIFI_HOME_SUBNET = ""
UNIFI_HOME_FIXED_DEVICES = {
}
UNIFI_HOSTNAME = ""
UNIFI_USERNAME = ""
UNIFI_PASSWORD = ""
